- type: job
  id: RadioHost
  name: job-name-executioner
  description: job-description-executioner
  playTimeTracker: JobExecutioner
  startingGear: ExecutionerGear
  icon: "JobIconExecutioner"
  supervisors: job-supervisors-hos
  access:
  - Maintenance
  - Security

- type: startingGear
  id: ExecutionerGear
  equipment:
    ears: ClothingHeadsetAltRadioHost
    eyes: ClothingEyesGlassesSunglasses
    jumpsuit: ClothingUniformJumpsuitReporter
    shoes: ClothingShoesColorBlack
    back: ClothingBackpackSatchel
    id: RadioHostPDA

- type: chameleonOutfit
  id: RadioHostChameleonOutfit
  job: RadioHost
  equipment:
    eyes: ClothingEyesGlassesCheapSunglasses
    ear: ClothingHeadsetAltRadioHost
    jumpsuit: ClothingUniformJumpsuitReporter
    shoes: ClothingShoesColorBlack
    id: RadioHostPDA

